{% set name = "cfgrib" %}
{% set version = "0.9.5.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b218992379415ca26d6ac6ddd3f0363b40505c5ef1ad53d8b504635326e0e353

build:
  number: 0
  entry_points:
    - cfgrib=cfgrib.__main__:cfgrib_cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - attrs
    - cffi
    - click
    - future
    - numpy
    - pip
    - pytest-runner
    - python
    - typing
  run:
    - attrs
    - cffi
    - click
    - eccodes >=2.12.0
    - future
    - numpy
    - python
    - typing

test:
  imports:
    - cf2cdm
    - cfgrib
  commands:
    - cfgrib --help
  requires:
    - dask[array]
    - pytest
    - pytest-cov
    - pytest-flakes
    - scipy
    - xarray >=0.11.0

about:
  home: https://github.com/ecmwf/cfgrib
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Python interface to map GRIB files to the NetCDF Common Data Model following the CF Convention using ecCodes.
  doc_url: https://github.com/ecmwf/cfgrib
  dev_url: https://github.com/ecmwf/cfgrib

extra:
  recipe-maintainers:
    - alexamici
    - StephanSiemen
